name: Go

on:
  push:
    branches: [ main ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        project_path: claat
        build_command: make release
        compress_assets: OFF
        release_name: latest
        #extra_files: claat/bin/VERSION sha1sum.txt nb2cl
