name: Go

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
    - name: build
      run: make release
      working-directory: ./claat

    - name: upload
      run: gh release upload ${{ github.event.release.tag_name }} ./claat/bin/*

